name: segmentation
channels:
- conda-forge
- nvidia
- pytorch
dependencies:
- _openmp_mutex=4.5=7_kmp_llvm
- aom=3.9.1=hac33072_0
- blas=1.0=mkl
- brotli-python=1.2.0=py311h66f275b_1
- bzip2=1.0.8=hda65f42_8
- ca-certificates=2025.11.12=hbd8a1cb_0
- certifi=2025.11.12=pyhd8ed1ab_0
- cffi=2.0.0=py311h03d9500_1
- charset-normalizer=3.4.4=pyhd8ed1ab_0
- cpython=3.11.14=py311hd8ed1ab_2
- cuda-cudart=11.8.89=0
- cuda-cudart_linux-64=12.4.127=h85509e4_2
- cuda-cupti=11.8.87=0
- cuda-libraries=11.8.0=0
- cuda-nvrtc=11.8.89=0
- cuda-nvtx=11.8.86=0
- cuda-opencl=12.4.127=he02047a_1
- cuda-runtime=11.8.0=0
- cuda-version=12.4=h3060b56_3
- dav1d=1.2.1=hd590300_0
- ffmpeg=4.3=hf484d3e_0
- filelock=3.20.0=pyhd8ed1ab_0
- fmt=12.0.0=h2b0788b_0
- freetype=2.12.1=h267a509_2
- fsspec=2025.10.0=pyhd8ed1ab_0
- giflib=5.2.2=hd590300_0
- gmp=6.3.0=hac33072_2
- gmpy2=2.2.1=py311h92a432a_2
- gnutls=3.6.13=h85f3911_1
- h2=4.3.0=pyhcf101f3_0
- hpack=4.1.0=pyhd8ed1ab_0
- hyperframe=6.1.0=pyhd8ed1ab_0
- icu=73.2=h59595ed_0
- idna=3.11=pyhd8ed1ab_0
- jinja2=3.1.6=pyhcf101f3_1
- lame=3.100=h166bdaf_1003
- lcms2=2.16=hb7c19ff_0
- ld_impl_linux-64=2.45=bootstrap_ha15bf96_4
- lerc=4.0.0=h0aef613_1
- libabseil=20250512.1=cxx17_hba17884_0
- libavif16=1.3.0=h6395336_2
- libblas=3.9.0=20_linux64_mkl
- libcblas=3.9.0=20_linux64_mkl
- libcublas=11.11.3.6=0
- libcufft=10.9.0.58=0
- libcufile=1.9.1.3=he02047a_2
- libcurand=10.3.5.147=he02047a_2
- libcusolver=11.4.1.48=0
- libcusparse=11.7.5.86=0
- libde265=1.0.15=h00ab1b0_0
- libdeflate=1.20=hd590300_0
- libexpat=2.7.3=hecca717_0
- libffi=3.5.2=h9ec8514_0
- libgcc=15.2.0=he0feb66_14
- libgcc-ng=15.2.0=h69a702a_14
- libheif=1.19.7=gpl_hc18d805_100
- libhwloc=2.11.2=default_he43201b_1000
- libiconv=1.18=h3b78370_2
- libjpeg-turbo=3.1.2=hb03c661_0
- liblapack=3.9.0=20_linux64_mkl
- liblzma=5.8.1=hb9d3cd8_2
- liblzma-devel=5.8.1=hb9d3cd8_2
- libnpp=11.8.0.86=0
- libnsl=2.0.1=hb9d3cd8_1
- libnvfatbin=12.4.127=he02047a_2
- libnvjitlink=12.4.127=he02047a_2
- libnvjpeg=11.9.0.86=0
- libpng=1.6.43=h2797004_0
- libprotobuf=3.21.12=hfc55251_2
- libsqlite=3.46.0=hde9e2c9_0
- libstdcxx=15.2.0=h934c35e_14
- libstdcxx-ng=15.2.0=hdf11a46_14
- libtiff=4.6.0=h1dd3fc0_3
- libuuid=2.41.2=he9a06e4_0
- libuv=1.51.0=hb03c661_1
- libwebp-base=1.6.0=hd42ef1d_0
- libxcb=1.15=h0b41bf4_0
- libxcrypt=4.4.36=hd590300_1
- libxml2=2.12.7=hc051c1a_1
- libzlib=1.2.13=h4ab18f5_6
- llvm-openmp=15.0.7=h0cdce71_0
- markupsafe=3.0.3=py311h3778330_0
- mkl=2023.2.0=ha770c72_50498
- mpc=1.3.1=h24ddda3_1
- mpfr=4.2.1=h90cbb55_3
- mpmath=1.3.0=pyhd8ed1ab_1
- ncurses=6.5=h2d0b736_3
- nettle=3.6=he412f7d_0
- networkx=3.6=pyhcf101f3_0
- numpy=2.3.5=py311h2e04523_0
- ocl-icd=2.3.3=hb9d3cd8_0
- opencl-headers=2025.06.13=h5888daf_0
- openh264=2.1.1=h780b84a_0
- openjpeg=2.5.2=h488ebb8_0
- openssl=3.6.0=h26f9b46_0
- optree=0.18.0=py311hdf67eae_0
- pillow=10.3.0=py311h18e6fac_0
- pip=25.3=pyh8b19718_0
- pthread-stubs=0.4=hb9d3cd8_1002
- pybind11=3.0.1=pyh7a1b43c_0
- pybind11-abi=11=hc364b38_1
- pybind11-global=3.0.1=pyhc7ab6ef_0
- pycparser=2.22=pyh29332c3_1
- pysocks=1.7.1=pyha55dd90_7
- python=3.11.9=hb806964_0_cpython
- python_abi=3.11=8_cp311
- pytorch=2.4.1=py3.11_cuda11.8_cudnn9.1.0_0
- pytorch-cuda=11.8=h7e8668a_6
- pytorch-mutex=1.0=cuda
- pyyaml=6.0.3=py311h3778330_0
- rav1e=0.7.1=h8fae777_3
- readline=8.2=h8c095d6_2
- requests=2.32.5=pyhd8ed1ab_0
- setuptools=80.9.0=pyhff2d567_0
- sleef=3.9.0=ha0421bc_0
- svt-av1=3.1.2=hecca717_0
- sympy=1.14.0=pyh2585a3b_105
- tbb=2021.13.0=hceb3a55_1
- tk=8.6.13=noxft_h4845f30_101
- torchaudio=2.4.1=py311_cu118
- torchtriton=3.0.0=py311
- torchvision=0.19.1=py311_cu118
- typing-extensions=4.15.0=h396c80c_0
- typing_extensions=4.15.0=pyhcf101f3_0
- tzdata=2025b=h78e105d_0
- urllib3=2.5.0=pyhd8ed1ab_0
- wheel=0.45.1=pyhd8ed1ab_1
- x265=3.5=h924138e_3
- xorg-libxau=1.0.12=hb03c661_1
- xorg-libxdmcp=1.1.5=hb03c661_1
- xz=5.8.1=hbcc6ac9_2
- xz-gpl-tools=5.8.1=hbcc6ac9_2
- xz-tools=5.8.1=hb9d3cd8_2
- yaml=0.2.5=h280c20c_3
- zlib=1.2.13=h4ab18f5_6
- zlib-ng=2.3.1=hde8ca8f_0
- zstandard=0.23.0=py311h49ec1c0_3
- zstd=1.5.6=ha6fb4c9_0

